version: '3'

networks:
  default:

services:
  template:
    build:
      context: .
      dockerfile: ./Template/Dockerfile
    ports:
      - 6006:6006
      - 5000:5000
      - 7687:7687
      - 1337:1337
      - 7474:7474
    volumes:
      - ./Template:/Template
    networks:
      - default
    tty: true

