version: '3'

networks:
  default:

services:
  dataset_generator:
    build:
      context: .
      dockerfile: ./dataset_generator/Dockerfile
    volumes:
      - ./dataset_generator:/dataset_generator
    networks:
      - default
    tty: true

  template:
    build:
      context: .
      dockerfile: ./template/Dockerfile
    ports:
      - 5000:5000
      - 7687:7687
      - 1337:1337
      - 7474:7474
    volumes:
      - ./template:/template
    networks:
      - default
    tty: true

